### ISSUE TITLE
Make it possible to change Atk's format

### ISSUE THREAD

**Issue by madskjeldgaard** [ambisonictoolkit/atk-sc3#106] opened 2021-09-24 10:08 UTC
Hello

As far as I can see, it's not possible to change Atk's format at the moment. I'd really like it to be `\ambix` so it matches IEM's plugins and others. 

As far as I can tell, the class variable `AtkHoa.format` is hardcoded and only has a getter and not a setter. Or did I overlook a method somewhere? 

Thanks  and best regards

**Comment by joslloand** [comment] 2021-09-24 20:10
Hello @madskjeldgaard,

I'm going to close this as an issue, as the ATK's default encoding format is:

```
AtkHoa.defaultOrder.postln;  // -> 3
AtkHoa.ordering.postln;  // -> acn
AtkHoa.normalisation.postln;  // -> n3d
AtkHoa.refRadius.postln;  // -> 1.5
```

As a workflow (and codebase), we've decided to keep things as _simple as possible_ by just observing one encoding convention. By design, we _do_ include robust and verbosely documented [Ambisonic Format Exchange](https://depts.washington.edu/dxscdoc/Help/Guides/Format-Exchange.html) functionality, which allows us to move between signal conventions used by other libraries.

I expect you'll have seen my https://github.com/ambisonictoolkit/atk-sc3/issues/95#issuecomment-926885361. I'll go ahead and link back to this (closed) issue, as a reminder to include some further discussion on interfacing with the [IEM BinauralDecoder](https://git.iem.at/audioplugins/IEMPluginSuite/-/tree/master/BinauralDecoder).

Thanks!

**Closed by joslloand** 2021-09-24 20:10 UTC

**Comment by madskjeldgaard** [comment] 2021-09-25 09:21
> Hello @madskjeldgaard,
> 
> I'm going to close this as an issue, as the ATK's default encoding format is:
> 
> ```
> AtkHoa.defaultOrder.postln;  // -> 3
> AtkHoa.ordering.postln;  // -> acn
> AtkHoa.normalisation.postln;  // -> n3d
> AtkHoa.refRadius.postln;  // -> 1.5
> ```
> 
> As a workflow (and codebase), we've decided to keep things as _simple as possible_ by just observing one encoding convention. By design, we _do_ include robust and verbosely documented [Ambisonic Format Exchange](https://depts.washington.edu/dxscdoc/Help/Guides/Format-Exchange.html) functionality, which allows us to move between signal conventions used by other libraries.
> 
> I expect you'll have seen my [#95 (comment)](https://github.com/ambisonictoolkit/atk-sc3/issues/95#issuecomment-926885361). I'll go ahead and link back to this (closed) issue, as a reminder to include some further discussion on interfacing with the [IEM BinauralDecoder](https://git.iem.at/audioplugins/IEMPluginSuite/-/tree/master/BinauralDecoder).
> 
> Thanks!

That makes sense. Thanks a lot for the clarification !
